
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwwrshsnzcclfbbfzkbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3d3JzaHNuemNjbGZiYmZ6a2JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMTI3ODIsImV4cCI6MjA2MjY4ODc4Mn0.ImYPihA8FYEIHoOSO-GrIjtKH9tgBDMBTNWPTJBaM_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
