export type Database = {
  public: {
    Tables: {
      vessels: {
        Row: {
          id: string;
          company_id: string | null;
          user_id: string | null;
          name: string;
          registration_number: string;
          type: string;
          captain_name: string | null;
          captain_user_id: string | null;
          capacity: number | null;
          length: number | null;
          created_at: string;
          crew_count: number | null;
          fishing_method: string | null;
          fishing_gear: Record<string, unknown> | null;
          engine_power: string | null;
          owner_name: string | null;
          width: string | null;
          fishery_permit: string | null;
          expiration_date: string | null;
          fileUrl: string | null;
          materials: string | null;
          draught: string | null;
          gross_tonnage: string | null;
          number_engines: string | null;
          type_of_machine: string | null;
          port_registry: string | null;
          owner_id: string | null;
          type_of_vessel: string | null;
          residential_address: string | null;
          image_url: string | null;
          latitude: string | null;
          longitude: string | null;
          current_zone: string | null;
        };
        Insert: {
          id?: string;
          company_id?: string | null;
          user_id?: string | null;
          name: string;
          registration_number: string;
          type: string;
          captain_name?: string | null;
          captain_user_id?: string | null;
          capacity?: number | null;
          length?: number | null;
          created_at?: string;
          crew_count?: number | null;
          fishing_method?: string | null;
          fishing_gear?: Record<string, unknown> | null;
          engine_power?: string | null;
          owner_name?: string | null;
          width?: string | null;
          fishery_permit?: string | null;
          expiration_date?: string | null;
          fileUrl?: string | null;
          materials?: string | null;
          draught?: string | null;
          gross_tonnage?: string | null;
          number_engines?: string | null;
          type_of_machine?: string | null;
          port_registry?: string | null;
          owner_id?: string | null;
          type_of_vessel?: string | null;
          residential_address?: string | null;
          image_url?: string | null;
          latitude?: string | null;
          longitude?: string | null;
          current_zone?: string | null;
        };
        Update: {
          id?: string;
          company_id?: string | null;
          user_id?: string | null;
          name?: string;
          registration_number?: string;
          type?: string;
          captain_name?: string | null;
          captain_user_id?: string | null;
          capacity?: number | null;
          length?: number | null;
          created_at?: string;
          crew_count?: number | null;
          fishing_method?: string | null;
          fishing_gear?: Record<string, unknown> | null;
          engine_power?: string | null;
          owner_name?: string | null;
          width?: string | null;
          fishery_permit?: string | null;
          expiration_date?: string | null;
          fileUrl?: string | null;
          materials?: string | null;
          draught?: string | null;
          gross_tonnage?: string | null;
          number_engines?: string | null;
          type_of_machine?: string | null;
          port_registry?: string | null;
          owner_id?: string | null;
          type_of_vessel?: string | null;
          residential_address?: string | null;
          image_url?: string | null;
          latitude?: string | null;
          longitude?: string | null;
          current_zone?: string | null;
        };
      };
      fishing_trips: {
        Row: {
          id: string;
          trip_code: string;
          user_id: string;
          vessel_id: string | null;
          vessel: string;
          address: string | null;
          departure_date: string | null;
          return_date: string | null;
          departure_port: string | null;
          departure_port_name: string | null;
          return_port: string | null;
          status: string;
          form_code: string;
          created_at: string;
          departure_province: string | null;
          place_of_departure: string | null;
          to_region: string | null;
          trip_period: string | null;
          number_of_crew: string | null;
          vessel_type: string | null;
          vessel_registration_number: string | null;
          docking_id: string | null;
          dock_province: string | null;
          place_of_dock: string | null;
          docking_date: string | null;
          total_trip_period: string | null;
          dock_code: string | null;
          fishing_logbook: string | null;
          trading_logbook: string | null;
          transshipment_logbook: string | null;
          owner_name: string | null;
        };
        Insert: {
          id?: string;
          vessel_id?: string | null;
          user_id: string;
          vessel: string;
          trip_code: string;
          address: string | null;
          departure_port_name: string | null;
          departure_date?: string | null;
          return_date?: string | null;
          departure_port?: string | null;
          return_port?: string | null;
          status: string;
          form_code: string;
          created_at?: string;
          departure_province?: string | null;
          place_of_departure?: string | null;
          to_region?: string | null;
          trip_period?: string | null;
          number_of_crew?: string | null;
          vessel_type?: string | null;
          vessel_registration_number?: string | null;
          docking_id?: string | null;
          dock_province?: string | null;
          place_of_dock?: string | null;
          docking_date?: string | null;
          total_trip_period?: string | null;
          dock_code?: string | null;
          fishing_logbook?: string | null;
          trading_logbook?: string | null;
          transshipment_logbook?: string | null;
          owner_name?: string | null;
        };
        Update: {
          id?: string;
          vessel_id?: string;
          user_id?: string;
          trip_code?: string;
          vessel: string;
          departure_port_name: string | null;
          address: string | null;
          departure_date?: string | null;
          return_date?: string | null;
          departure_port?: string | null;
          return_port?: string | null;
          status?: string;
          form_code?: string;
          created_at?: string;
          departure_province?: string | null;
          place_of_departure?: string | null;
          to_region?: string | null;
          trip_period?: string | null;
          number_of_crew?: string | null;
          vessel_type?: string | null;
          vessel_registration_number?: string | null;
          docking_id?: string | null;
          dock_province?: string | null;
          place_of_dock?: string | null;
          docking_date?: string | null;
          total_trip_period?: string | null;
          dock_code?: string | null;
          fishing_logbook?: string | null;
          trading_logbook?: string | null;
          transshipment_logbook?: string | null;
          owner_name?: string | null;
        };
      };
      fuel_consumption: {
        Row: {
          id: number;
          trip_id: string | null;
          vessel_id: string | null;
          name: string | null;
          start_mileage: number | null;
          end_mileage: number | null;
          refueling_volume: number | null;
          remarks: string | null;
          created_at: string | null;
          fuel_consumption: string | null;
          refueling_date: string | null;
        };
        Insert: {
          id?: number;
          trip_id?: string | null;
          vessel_id?: string | null;
          name?: string | null;
          start_mileage?: number | null;
          end_mileage?: number | null;
          refueling_volume?: number | null;
          remarks?: string | null;
          created_at?: string | null;
          fuel_consumption?: string | null;
          refueling_date?: string | null;
        };
        Update: {
          id?: number;
          trip_id?: string | null;
          vessel_id?: string | null;
          name?: string | null;
          start_mileage?: number | null;
          end_mileage?: number | null;
          refueling_volume?: number | null;
          remarks?: string | null;
          created_at?: string | null;
          fuel_consumption?: string | null;
          refueling_date?: string | null;
        };
      };
      catch_records: {
        Row: {
          id: string;
          haul_id: string;
          species: string;
          quantity: number;
          unit: string;
          quality: string | null;
          processing_method: string | null;
          catching_location: string | null;
          qr_code: string;
          created_at: string;
          fish_name: string | null;
          fish_specie: string | null;
          fish_size: string | null;
          diameter: string | null;
          fish_product_id: string | null;
          farmer_id: string | null;
          capture_date: string | null;
          capture_time: string | null;
          capture_zone: string | null;
          case_size: string | null;
          net_kg_per_case: string | null;
          tank: string | null;
          three_a_code: string | null;
          updated_at: string | null;
          image_url: string | null;
          latitude: string | null;
          longitude: string | null;
          region: string | null;
          case_quantity: string | null;
        };
        Insert: {
          id?: string;
          haul_id: string;
          species: string;
          quantity: number;
          unit?: string;
          quality?: string | null;
          processing_method?: string | null;
          catching_location?: string | null;
          qr_code: string;
          created_at?: string;
          fish_name?: string | null;
          fish_specie?: string | null;
          fish_size?: string | null;
          diameter?: string | null;
          fish_product_id?: string | null;
          farmer_id?: string | null;
          capture_date?: string | null;
          capture_time?: string | null;
          capture_zone?: string | null;
          case_size?: string | null;
          net_kg_per_case?: string | null;
          tank?: string | null;
          three_a_code?: string | null;
          updated_at?: string | null;
          image_url?: string | null;
          latitude?: string | null;
          longitude?: string | null;
          region?: string | null;
          case_quantity?: string | null;
        };
        Update: {
          id?: string;
          haul_id?: string;
          species?: string;
          quantity?: number;
          unit?: string;
          quality?: string | null;
          processing_method?: string | null;
          catching_location?: string | null;
          qr_code?: string;
          created_at?: string;
          fish_name?: string | null;
          fish_specie?: string | null;
          fish_size?: string | null;
          diameter?: string | null;
          fish_product_id?: string | null;
          farmer_id?: string | null;
          capture_date?: string | null;
          capture_time?: string | null;
          capture_zone?: string | null;
          case_size?: string | null;
          net_kg_per_case?: string | null;
          tank?: string | null;
          three_a_code?: string | null;
          updated_at?: string | null;
          image_url?: string | null;
          latitude?: string | null;
          longitude?: string | null;
          region?: string | null;
          case_quantity?: string | null;
        };
      };
      fishing_hauls: {
        Row: {
          id: string;
          trip_id: string;
          haul_number: number;
          start_time: string | null;
          end_time: string | null;
          latitude: number | null;
          longitude: number | null;
          depth: number | null;
          notes: string | null;
          qr_code: string;
          created_at: string;
          farmer_id: string | null;
        };
        Insert: {
          id?: string;
          trip_id: string;
          haul_number: number;
          start_time?: string | null;
          end_time?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          depth?: number | null;
          notes?: string | null;
          qr_code: string;
          created_at?: string;
          farmer_id?: string | null;
        };
        Update: {
          id?: string;
          trip_id?: string;
          haul_number?: number;
          start_time?: string | null;
          end_time?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          depth?: number | null;
          notes?: string | null;
          qr_code?: string;
          created_at?: string;
          farmer_id?: string | null;
        };
      };
      companies: {
        Row: {
          id: string;
          user_id: string;
          address: string | null;
          created_at: string;
          address_new: string | null;
          company_name: string | null;
          rep_phone: string | null;
          representative_email: string | null;
          representative_name: string | null;
          representative_position: string | null;
          tax_code: string | null;
          imageOne: string | null;
          imageTwo: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          address?: string | null;
          created_at?: string;
          address_new?: string | null;
          company_name?: string | null;
          rep_phone?: string | null;
          representative_email?: string | null;
          representative_name?: string | null;
          representative_position?: string | null;
          tax_code?: string | null;
          imageOne?: string | null;
          imageTwo?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          address?: string | null;
          created_at?: string;
          address_new?: string | null;
          company_name?: string | null;
          rep_phone?: string | null;
          representative_email?: string | null;
          representative_name?: string | null;
          representative_position?: string | null;
          tax_code?: string | null;
          imageOne?: string | null;
          imageTwo?: string | null;
        };
      };
      crew_members: {
        Row: {
          id: string;
          vessel_id: string;
          name: string;
          position: string;
          phone: string | null;
          id_card: string | null;
          created_at: string;
          id_card_front: string | null;
          id_card_back: string | null;
          role: string | null;
        };
        Insert: {
          id?: string;
          vessel_id: string;
          name: string;
          position: string;
          phone?: string | null;
          id_card?: string | null;
          created_at?: string;
          id_card_front?: string | null;
          id_card_back?: string | null;
          role?: string | null;
        };
        Update: {
          id?: string;
          vessel_id?: string;
          name?: string;
          position?: string;
          phone?: string | null;
          id_card?: string | null;
          created_at?: string;
          id_card_front?: string | null;
          id_card_back?: string | null;
          role?: string | null;
        };
      };
      fishing_methods: {
        Row: {
          id: string;
          vessel_id: string;
          method_name: string;
          gear_type: string;
          description: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          vessel_id: string;
          method_name: string;
          gear_type: string;
          description?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          vessel_id?: string;
          method_name?: string;
          gear_type?: string;
          description?: string | null;
          created_at?: string;
        };
      };
      seaports: {
        Row: {
          id: string;
          name: string;
          address: string | null;
          classification: number | null;
          province: string | null;
          district: string | null;
          ward: string | null;
          status: string | null;
          latitude: number | null;
          longitude: number | null;
          image_url: string | null;
          created_at: string | null;
          updated_at: string | null;
          number: number;
        };
        Insert: {
          id?: string;
          name: string;
          address?: string | null;
          classification?: number | null;
          province?: string | null;
          district?: string | null;
          ward?: string | null;
          status?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          image_url?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          number?: number;
        };
        Update: {
          id?: string;
          name?: string;
          address?: string | null;
          classification?: number | null;
          province?: string | null;
          district?: string | null;
          ward?: string | null;
          status?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          image_url?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          number?: number;
        };
      };
      users: {
        Row: {
          id: string;
          auth_id: string | null;
          email: string;
          name: string;
          is_approved: boolean | null;
          is_email_verified: boolean | null;
          is_phone_verified: boolean | null;
          phone: string | null;
          created_at: string | null;
          updated_at: string | null;
          grant_id: string | null;
          role: string | null;
          account_type: string | null;
          account_package: string | null;
          default_vessel: string | null;
        };
        Insert: {
          id?: string;
          auth_id?: string | null;
          email: string;
          name: string;
          is_approved?: boolean | null;
          is_email_verified?: boolean | null;
          is_phone_verified?: boolean | null;
          phone?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          grant_id?: string | null;
          role?: string | null;
          account_type?: string | null;
          account_package?: string | null;
          default_vessel?: string | null;
        };
        Update: {
          id?: string;
          auth_id?: string | null;
          email?: string;
          name?: string;
          is_approved?: boolean | null;
          is_email_verified?: boolean | null;
          is_phone_verified?: boolean | null;
          phone?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          grant_id?: string | null;
          role?: string | null;
          account_type?: string | null;
          account_package?: string | null;
          default_vessel?: string | null;
        };
      };
      vessel_transactions: {
        Row: {
          id: string;
          seller_vessel_id: string;
          buyer_vessel_id: string;
          catch_record_id: string | null;
          quantity: number;
          unit: string;
          price: number | null;
          currency: string | null;
          status: string;
          qr_code: string;
          transaction_date: string;
          created_at: string;
          trip_id: string | null;
          type: string | null;
          items: Record<string, unknown>[] | null;
        };
        Insert: {
          id?: string;
          seller_vessel_id: string;
          buyer_vessel_id: string;
          catch_record_id?: string | null;
          quantity: number;
          unit?: string;
          price?: number | null;
          currency?: string | null;
          status?: string;
          qr_code: string;
          transaction_date?: string;
          created_at?: string;
          trip_id?: string | null;
          type?: string | null;
          items?: Record<string, unknown>[] | null;
        };
        Update: {
          id?: string;
          seller_vessel_id?: string;
          buyer_vessel_id?: string;
          catch_record_id?: string | null;
          quantity?: number;
          unit?: string;
          price?: number | null;
          currency?: string | null;
          status?: string;
          qr_code?: string;
          transaction_date?: string;
          created_at?: string;
          trip_id?: string | null;
          type?: string | null;
          items?: Record<string, unknown>[] | null;
        };
      };
      processing_records: {
        Row: {
          id: string;
          company_id: string;
          catch_record_id: string | null;
          vessel_transaction_id: string | null;
          processing_date: string;
          product_type: string;
          input_quantity: number;
          output_quantity: number;
          processing_method: string;
          packaging_type: string | null;
          storage_temperature: number | null;
          qr_code: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          company_id: string;
          catch_record_id?: string | null;
          vessel_transaction_id?: string | null;
          processing_date?: string;
          product_type: string;
          input_quantity: number;
          output_quantity: number;
          processing_method: string;
          packaging_type?: string | null;
          storage_temperature?: number | null;
          qr_code?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          company_id?: string;
          catch_record_id?: string | null;
          vessel_transaction_id?: string | null;
          processing_date?: string;
          product_type?: string;
          input_quantity?: number;
          output_quantity?: number;
          processing_method?: string;
          packaging_type?: string | null;
          storage_temperature?: number | null;
          qr_code?: string;
          created_at?: string;
        };
      };
      product_orders: {
        Row: {
          id: string;
          trip_id: string;
          tank_number: number;
          product_name: string;
          product_id: string;
          size: number;
          stock: number;
          type: string;
          quantity_load: number | null;
          available_load: number | null;
          price: number | null;
          bid_price: number | null;
          departure_date: string | null;
          arrival_date: string | null;
          status: string;
          created_at: string | null;
          auth_id: string | null;
          catch_id: string | null;
          catch_record_ids: string[] | null;
          departure_port: string | null;
          to_port: string | null;
          zone_dept: string | null;
          items: Record<string, unknown>[] | null;
        };
        Insert: {
          id?: string;
          trip_id: string;
          tank_number: number;
          product_name: string;
          product_id: string;
          size: number;
          stock: number;
          type: string;
          quantity_load?: number | null;
          available_load?: number | null;
          price?: number | null;
          bid_price?: number | null;
          departure_date?: string | null;
          arrival_date?: string | null;
          status?: string;
          created_at?: string | null;
          auth_id?: string | null;
          catch_id: string | null;
          catch_record_ids?: string[] | null;
          departure_port?: string | null;
          to_port?: string | null;
          zone_dept?: string | null;
          items?: Record<string, unknown>[] | null;
        };
        Update: {
          id?: string;
          trip_id?: string;
          tank_number?: number;
          product_name?: string;
          product_id?: string;
          size?: number;
          stock?: number;
          type?: string;
          quantity_load?: number | null;
          available_load?: number | null;
          price?: number | null;
          bid_price?: number | null;
          departure_date?: string | null;
          arrival_date?: string | null;
          status?: string;
          created_at?: string | null;
          auth_id?: string | null;
          catch_id: string | null;
          catch_record_ids?: string[] | null;
          departure_port?: string | null;
          to_port?: string | null;
          zone_dept?: string | null;
          items?: Record<string, unknown>[] | null;
        };
      };
      vessel_locations: {
        Row: {
          id: string;
          vessel_id: string;
          latitude: number;
          longitude: number;
          heading: number | null;
          speed: number | null;
          timestamp: string;
        };
        Insert: {
          id?: string;
          vessel_id: string;
          latitude: number;
          longitude: number;
          heading?: number | null;
          speed?: number | null;
          timestamp?: string;
        };
        Update: {
          id?: string;
          vessel_id?: string;
          latitude?: number;
          longitude?: number;
          heading?: number | null;
          speed?: number | null;
          timestamp?: string;
        };
      };
      grant_links: {
        Row: {
          id: string;
          vessel_id: string | null;
          crew_id: string | null;
          role: string;
          grant_code: string;
          is_used: boolean | null;
          created_at: string | null;
          used_at: string | null;
          granted_by: string | null;
          email: string | null;
          status: string | null;
        };
        Insert: {
          id?: string;
          vessel_id?: string | null;
          crew_id?: string | null;
          role: string;
          grant_code: string;
          is_used?: boolean | null;
          created_at?: string | null;
          used_at?: string | null;
          granted_by?: string | null;
          email?: string | null;
          status?: string | null;
        };
        Update: {
          id?: string;
          vessel_id?: string | null;
          crew_id?: string | null;
          role?: string;
          grant_code?: string;
          is_used?: boolean | null;
          created_at?: string | null;
          used_at?: string | null;
          granted_by?: string | null;
          email?: string | null;
          status?: string | null;
        };
      };
      ocr_documents: {
        Row: {
          id: string;
          user_id: string | null;
          file_path: string;
          registration_number: string;
          vessel_name: string | null;
          owner_name: string | null;
          engine_power: string | null;
          length: string | null;
          width: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          file_path: string;
          registration_number: string;
          vessel_name?: string | null;
          owner_name?: string | null;
          engine_power?: string | null;
          length?: string | null;
          width?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          file_path?: string;
          registration_number?: string;
          vessel_name?: string | null;
          owner_name?: string | null;
          engine_power?: string | null;
          length?: string | null;
          width?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      user_locations: {
        Row: {
          id: string;
          user_id: string;
          latitude: number;
          longitude: number;
          accuracy: number | null;
          heading: number | null;
          speed: number | null;
          timestamp: string;
          created_at: string | null;
          zone: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          latitude: number;
          longitude: number;
          accuracy?: number | null;
          heading?: number | null;
          speed?: number | null;
          timestamp?: string;
          created_at?: string | null;
          zone?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          latitude?: number;
          longitude?: number;
          accuracy?: number | null;
          heading?: number | null;
          speed?: number | null;
          timestamp?: string;
          created_at?: string | null;
          zone?: string | null;
        };
      };
      local_shipment2retailer: {
        Row: {
          id: string;
          user_id: string;
          retailer_id: string | null;
          retailer_name: string | null;
          retailer_delivery_address: string | null;
          retailer_loading: string | null;
          retailer_case: number | null;
          retailer_loading_kg: number | null;
          local_transport_cost: number | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          retailer_id?: string | null;
          retailer_name?: string | null;
          retailer_delivery_address?: string | null;
          retailer_loading?: string | null;
          retailer_case?: number | null;
          retailer_loading_kg?: number | null;
          local_transport_cost?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          retailer_id?: string | null;
          retailer_name?: string | null;
          retailer_delivery_address?: string | null;
          retailer_loading?: string | null;
          retailer_case?: number | null;
          retailer_loading_kg?: number | null;
          local_transport_cost?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      sea_logistics: {
        Row: {
          id: string;
          user_id: string;
          sea_port: number;
          offshore_fishing: number;
          sea_shipment_id: string;
          sea_loading_date: string | null;
          sea_loading_kg: number | null;
          sea_distance_km: number | null;
          sea_shipping_cost_per_kg: number | null;
          estimate_arrival_date: string | null;
          landing_date: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          sea_port: number;
          offshore_fishing: number;
          sea_shipment_id: string;
          sea_loading_date?: string | null;
          sea_loading_kg?: number | null;
          sea_distance_km?: number | null;
          sea_shipping_cost_per_kg?: number | null;
          estimate_arrival_date?: string | null;
          landing_date?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          sea_port?: number;
          offshore_fishing?: number;
          sea_shipment_id?: string;
          sea_loading_date?: string | null;
          sea_loading_kg?: number | null;
          sea_distance_km?: number | null;
          sea_shipping_cost_per_kg?: number | null;
          estimate_arrival_date?: string | null;
          landing_date?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      truck_logistics: {
        Row: {
          id: string;
          user_id: string;
          truck_shipment_id: string;
          date_pickup: string | null;
          address_pickup: string | null;
          truck_id: string | null;
          truck_type: string | null;
          driver_name: string | null;
          driver_phone: string | null;
          loading_case: number | null;
          product_id: string | null;
          loading_weight_kg: number | null;
          truck_distance_km: number | null;
          truck_shipping_cost_per_kg: number | null;
          shipping_warehouse_id: string | null;
          wh_address: string | null;
          receiving_kiosk_name: string | null;
          kiosk_id: string | null;
          kiosk_address: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          truck_shipment_id: string;
          date_pickup?: string | null;
          address_pickup?: string | null;
          truck_id?: string | null;
          truck_type?: string | null;
          driver_name?: string | null;
          driver_phone?: string | null;
          loading_case?: number | null;
          product_id?: string | null;
          loading_weight_kg?: number | null;
          truck_distance_km?: number | null;
          truck_shipping_cost_per_kg?: number | null;
          shipping_warehouse_id?: string | null;
          wh_address?: string | null;
          receiving_kiosk_name?: string | null;
          kiosk_id?: string | null;
          kiosk_address?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          truck_shipment_id?: string;
          date_pickup?: string | null;
          address_pickup?: string | null;
          truck_id?: string | null;
          truck_type?: string | null;
          driver_name?: string | null;
          driver_phone?: string | null;
          loading_case?: number | null;
          product_id?: string | null;
          loading_weight_kg?: number | null;
          truck_distance_km?: number | null;
          truck_shipping_cost_per_kg?: number | null;
          shipping_warehouse_id?: string | null;
          wh_address?: string | null;
          receiving_kiosk_name?: string | null;
          kiosk_id?: string | null;
          kiosk_address?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      settings: {
        Row: {
          id: number;
          otp_enabled: boolean;
        };
        Insert: {
          id?: number;
          otp_enabled?: boolean;
        };
        Update: {
          id?: number;
          otp_enabled?: boolean;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
